name: Deploy Web

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  pages: write
  id-token: write
  contents: read

jobs:
  build:
    name: Build Expo Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Export Expo Web with correct public URL
        env:
          CI: false
          LIGHTNINGCSS_IGNORE_NATIVE: 1
          EXPO_PUBLIC_URL: "https://qassim-coding.github.io/Listana"
        run: npx expo export --platform web --clear --output-dir dist

      - name: Rewrite asset URLs for GitHub Pages
        run: node scripts/fix-public-paths.cjs

      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
